### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by pkqpotter123** [IRMVLab/RegFormer#4]
Hello, I encountered the following issue while running the program. Has anyone else experienced this, or does anyone know how to solve it?
Traceback (most recent call last):
  File "RegFormer/train.py", line 411, in <module>
    main()
  File "RegFormer/train.py", line 167, in main
    l0_q, l0_t, l1_q, l1_t, l2_q, l2_t, l3_q, l3_t, pc1_ouput, q_gt, t_gt, w_x, w_q = model(pos2, pos1, T_gt, T_trans, T_trans_inv)
  File "anaconda3/envs/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "RegFormer/regformer_model.py", line 522, in forward
    l1_cost_volume = self.cost_volume3(l1_xyz_warp_proj_f1, l1_xyz_proj_f2, l1_points_warp_cross_proj_f1, l1_points_warp_cross_proj_f2) #FE1
  File "anaconda3/envs/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "RegFormer/conv_util.py", line 600, in forward
    pi_feat1_new_reshape = conv(pi_feat1_new_reshape)    
  File "anaconda3/envs/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "RegFormer/conv_util.py", line 83, in forward
    outputs = self.conv(x)
  File "anaconda3/envs/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "anaconda3/envs/env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "anaconda3/envs/env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

**Comment by liujiuming123** [comment]
I don't know whether the environment is established correctly. Don't worry, we will release our docker later.

**Comment by pkqpotter123** [comment]
Anyway, thank you for your response.

**Comment by pkqpotter123** [comment]
I've encountered an array index out-of-bounds issue. Do you happen to know a solution? Thanks a lot.
anaconda3/envs/torch2/bin/python RegFormer/demo.py 
anaconda3/envs/torch2/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [17,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [17,0,0], thread: [1,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [17,0,0], thread: [2,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [17,0,0], thread: [3,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [39,0,0], thread: [32,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [25,0,0], thread: [25,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "torchRegFormer/demo.py", line 34, in <module>
    l0_q, l0_t, l1_q, l1_t, l2_q, l2_t, l3_q, l3_t, pc1_ouput, q_gt, t_gt, w_x, w_q = model([pos2], [pos1], T_gt, None, None)
  File "/data/zzf/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "torchRegFormer/regformer_model.py", line 522, in forward
    l1_cost_volume = self.cost_volume3(l1_xyz_warp_proj_f1, l1_xyz_proj_f2, l1_points_warp_cross_proj_f1, l1_points_warp_cross_proj_f2) #FE1
  File "/data/zzf/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "torchRegFormer/conv_util.py", line 551, in forward
    qi_xyz_grouped = torch.gather(xyz2_bn3, 1, neighbor_idx.unsqueeze(-1).repeat(1, 1, 3))
RuntimeError: CUDA error: device-side assert triggered

Process finished with exit code 1
