### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by pkqpotter123** [IRMVLab/RegFormer#5]
I've encountered an array index out-of-bounds issue. Do you happen to know a solution? Thanks a lot.
anaconda3/envs/torch2/bin/python RegFormer/demo.py 
anaconda3/envs/torch2/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [17,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [17,0,0], thread: [1,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [17,0,0], thread: [2,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [17,0,0], thread: [3,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [39,0,0], thread: [32,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [25,0,0], thread: [25,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "torchRegFormer/demo.py", line 34, in <module>
    l0_q, l0_t, l1_q, l1_t, l2_q, l2_t, l3_q, l3_t, pc1_ouput, q_gt, t_gt, w_x, w_q = model([pos2], [pos1], T_gt, None, None)
  File "/data/zzf/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "torchRegFormer/regformer_model.py", line 522, in forward
    l1_cost_volume = self.cost_volume3(l1_xyz_warp_proj_f1, l1_xyz_proj_f2, l1_points_warp_cross_proj_f1, l1_points_warp_cross_proj_f2) #FE1
  File "/data/zzf/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "torchRegFormer/conv_util.py", line 551, in forward
    qi_xyz_grouped = torch.gather(xyz2_bn3, 1, neighbor_idx.unsqueeze(-1).repeat(1, 1, 3))
RuntimeError: CUDA error: device-side assert triggered

Process finished with exit code 1

_Originally posted by @pkqpotter123 in https://github.com/IRMVLab/RegFormer/issues/4#issuecomment-1846791500_

**Comment by whqweqwe** [comment]
Have you solved this problem?

**Comment by pkqpotter123** [comment]
I'm sorry, the issue has not been resolved yet. If there are any updates, feel free to communicate at any time.

**Comment by liujiuming123** [comment]
[requirements.txt](https://github.com/IRMVLab/RegFormer/files/13667518/requirements.txt)

**Comment by liujiuming123** [comment]
We release the docker environment list here. Hopefully it can address your problem.

**Comment by whqweqwe** [comment]
@pkqpotter123 How did you solve this problem: return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

**Comment by pkqpotter123** [comment]
> @pkqpotter123 你是如何解决这个问题的： return F.conv2d(input,weight,bias,self.stride, 运行时错误：cuDNN 错误：CUDNN_STATUS_INTERNAL_ERROR

I added the following line in the script: os.environ['CUDA_LAUNCH_BLOCKING'] = '1'。
The error CUDNN_STATUS_INTERNAL_ERROR is a general and non-specific error. The purpose of the code os.environ['CUDA_LAUNCH_BLOCKING'] = '1' is to make CUDA errors more detailed. After adding this line, the error became 'index out of bounds'

**Comment by pkqpotter123** [comment]
> We release the docker environment list here. Hopefully it can address your problem.

Thank you very much for your help.

**Comment by whqweqwe** [comment]
@pkqpotter123 Yes, but I used the author's requirements. txt and it still exists：perator(): block: [17,0,0], thread: [0,0,0] Assertion idx_dim >= 0 && idx_dim < index_size && "index out of bounds" failed.
Have you solved this problem？

**Comment by zlynpu** [comment]
@liujiuming123 When I was debugging, I found that neighbor_idx would become garbled as shown in the picture. What is the reason for this?
<img width="507" alt="1703084629418" src="https://github.com/IRMVLab/RegFormer/assets/103632029/1d627e09-e6ca-43d9-98d6-5d50c98909d4">
This is in lines 549~554 of conv_util.py

**Comment by zlynpu** [comment]
> @liujiuming123 When I was debugging, I found that neighbor_idx would become garbled as shown in the picture. What is the reason for this? <img alt="1703084629418" width="507" src="https://private-user-images.githubusercontent.com/103632029/291932278-1d627e09-e6ca-43d9-98d6-5d50c98909d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzg2OTksIm5iZiI6MTcwMzEzODM5OSwicGF0aCI6Ii8xMDM2MzIwMjkvMjkxOTMyMjc4LTFkNjI3ZTA5LWU2Y2EtNDNkOS05OGQ2LTVkNTBjOTg5MDlkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwNTU5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2NlM2Y3M2IzMjZjN2NiYTMzMTkzZjczNzAzZjU3ZjEzNTE4YmRjNDVhN2QwMjQ1M2U1MTEyYTgzMDQ2MjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j6olDnIfhZQstoyx9QWoXAo8bawkiTeU8EBzGZkQp4s"> This is in lines 549~554 of conv_util.py

And I would like to ask what is the difference between fused_conv_select_k and fused_conv_select_k_add in ops_torch

**Comment by liujiuming123** [comment]
We found that the index setting inside our CUDA operator was wrong when we debugged the codes, and we have corrected it now. You can try to compile them again. Hopefully, this can help you well.
